[project]
name = 'Decentralized-Manufacturing-Quality-Control'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.certification]
path = 'contracts/certification.clar'
clarity_version = 2
epoch = 2.5

[contracts.component-tracking]
path = 'contracts/component-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.defect-tracking]
path = 'contracts/defect-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.facility-verification]
path = 'contracts/facility-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.testing-protocol]
path = 'contracts/testing-protocol.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
